name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17'  # Update to Node.js 17 or later

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env:
          VITE_GITHUB_USUARIO: ${{ secrets.VITE_GITHUB_USUARIO }}
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          VITE_GITHUB_USUARIO: ${{ secrets.VITE_GITHUB_USUARIO }}
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
